trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  appName: 'yogapp-nathan'
  appServicePlan: 'yogapp-nathan-dev-001'
  resourceGroup: 'rg-stage-2022-yogapp-nathan'
  serviceConnection: 'svc-azure-nathan'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: AzureWebApp@1
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: '$(serviceConnection)'
      appName: '$(appName)'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      RuntimeStack: 'DOTNET|7.0'
      StartupCommand: 'dotnet my-dotnet7-api.dll'
#      slotName: 'production'
      ResourceGroupName: '$(resourceGroup)'
      AppServicePlan: '$(appServicePlan)'