trigger:
  - master
  
name: $(date:yyyyMMdd)$(rev:.r) ($(SourceBranchName).$(BuildId))

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
#  tag: '$(Build.SourceBranchName).$(Build.BuildId)'
  artifactName: 'yogapp-api'
#  publishFolder: 'yogapp-api-publish'
  subscription: 'fe2d2a77-9f7e-4def-9557-ba53b6f38cd0'
  appName: 'yogapp-nathan-api'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 7 SDK'
    inputs:
      version: '7.x'

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet packages'
    inputs:
      command: 'restore'
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '$(artifactName)'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure App Service'
    inputs:
      appType: 'webAppLinux'
      azureSubscription: '$(subscription)'
      appName: '$(appName)'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'